- name: make sure {{ username }} user exists
  become: yes
  user: name={{ username }} shell="{{ shell }}"

- name: Set up authorized_keys for {{ username }}
  become: yes
  tags:
    - ssh_grant_access
  authorized_key: user={{ username }}
                  key="{{ lookup('file', 'roles/user/public_keys/' + item) }}"
                  manage_dir=yes
  with_items: "{{ ssh_keys }}"

- name: user {{ username }} should have a colored prompt
  when: shell == "/bin/bash"
  remote_user: "{{ username }}"
  lineinfile: >
    dest=/home/{{ username }}/.bashrc
    state=present
    backrefs=yes
    regexp="^#force_color_prompt=yes$"
    line="force_color_prompt=yes"

- name: user {{ username }} should have a red prompt
  when:
    - green_prompt is not defined
    - shell == "/bin/bash"
  remote_user: "{{ username }}"
  lineinfile: >
    dest=/home/{{ username }}/.bashrc
    state=present
    backrefs=yes
    regexp="(\s*)(PS1=.*)(\[01;32m\\\])(.*)"
    line="\1\2[\033[01;31m\]\4"
